module.exports = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "i.imgur.com",
        port: "",
        pathname: "/*",
      },
    ],
  },

  async redirects() {
    return [
      {
        source: "/45_balliol_survey",
        destination: "https://forms.gle/pA7FkswzGZaNZyzCA",
        permanent: false,
        basePath: false,
      },
      {
        source: "/signup",
        destination: "https://forms.gle/8c6AXfLTANdFWU1c7",
        permanent: false,
        basePath: false,
      },
      {
        source: "/45_balliol_rent_increases",
        destination: "https://forms.gle/woMcddXv27CKFRU57",
        permanent: false,
        basePath: false,
      },
      {
        source: "/137_isabella_survey",
        destination: "https://forms.gle/FV3TPXUyZuB1TvSw8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/225_davisville_survey",
        destination: "https://forms.gle/LApEFx7s6iQ67iJ46",
        permanent: false,
        basePath: false,
      },
      {
        source: "/40_alexander_survey",
        destination: "https://forms.gle/ZdTQNSfbMVMUvxKD8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/50_alexander_survey",
        destination: "https://forms.gle/HGwTWKXrcqL3Z3PP6",
        permanent: false,
        basePath: false,
      },
      {
        source: "/55_maitland_survey",
        destination: "https://forms.gle/tk4MFrcFbi2DYoD2A",
        permanent: false,
        basePath: false,
      },
      {
        source: "/77_davisville_survey",
        destination: "https://forms.gle/X7ZETNPDch7NMgre7",
        permanent: false,
        basePath: false,
      },
      {
        source: "/222_esplanade_survey",
        destination: "https://forms.gle/h6fko2A7zkgmXap7A",
        permanent: false,
        basePath: false,
      },
      {
        source: "/158_front_survey",
        destination: "https://forms.gle/Fg9UYCyRnFPgBZaw8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/time_space_survey",
        destination: "https://forms.gle/6ZmyhmsaenmscwHy7",
        permanent: false,
        basePath: false,
      },
      {
        source: "/crescent_town_survey",
        destination: "https://forms.gle/eCgAReBaat2B6Ytt5",
        permanent: false,
        basePath: false,
      },
      {
        source: "/99_howard_survey",
        destination: "https://forms.gle/89LRokJPGnQHCuog8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/135_rose_survey",
        destination: "https://forms.gle/AekVgEoaX1Y5hWGr8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/565_sherbourne_survey",
        destination: "https://forms.gle/9iFLLraGvAZSaKj28",
        permanent: false,
        basePath: false,
      },
      {
        source: "/670_parliament_survey",
        destination: "https://forms.gle/4tcathTTXDFEqLkE8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/sherbourne_tenant_survey",
        destination: "https://forms.gle/yfzaxzWBFfAyzkcM9",
        permanent: false,
        basePath: false,
      },
      {
        source: "/7_crescent_pl_survey",
        destination: "https://forms.gle/4HJdm9mevX2sm6mPA",
        permanent: false,
        basePath: false,
      },
      {
        source: "/9_crescent_pl_survey",
        destination: "https://forms.gle/SGqAveagkpcEaEks9",
        permanent: false,
        basePath: false,
      },
      {
        source: "/11_crescent_pl_survey",
        destination: "https://forms.gle/UVUWwXzgDvrUgaUU8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/570_bay_survey",
        destination: "https://forms.gle/fBqGyMaZmUSUVyDq6",
        permanent: false,
        basePath: false,
      },
      {
        source: "/55_gerrard_survey",
        destination: "https://forms.gle/SBsmgurAAN9CHjiV7",
        permanent: false,
        basePath: false,
      },
      {
        source: "/545_sherbourne_survey",
        destination: "https://forms.gle/4mo6HyfXRtumjaNT6",
        permanent: false,
        basePath: false,
      },
      {
        source: "/561_sherbourne_survey",
        destination: "https://forms.gle/Z9rFWgqMkN73esv17",
        permanent: false,
        basePath: false,
      },
      {
        source: "/167_church_survey",
        destination: "https://forms.gle/wuThwegCgha7yqjQ7",
        permanent: false,
        basePath: false,
      },
      {
        source: "/191_sherbourne_survey",
        destination: "https://forms.gle/MmrT4iGEPm4hcuh18",
        permanent: false,
        basePath: false,
      },
      {
        source: "/350_queensquayw_survey",
        destination: "https://forms.gle/5onTe9c9SgA85f1j9",
        permanent: false,
        basePath: false,
      },
      {
        source: "/390_queensquayw_survey",
        destination: "https://forms.gle/YnaVSRpozLr1ywdX8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/1101_bay_survey",
        destination: "https://forms.gle/udNJjWpXWT46jXhx8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/14_carluke_survey",
        destination: "https://forms.gle/56dgUuyMg5duTeNWA",
        permanent: false,
        basePath: false,
      },
      {
        source: "/16_carluke_survey",
        destination: "https://forms.gle/ZRZN9zLfSQpWpcjj9",
        permanent: false,
        basePath: false,
      },
      {
        source: "/20_carluke_survey",
        destination: "https://forms.gle/xZPkQQEpRuvqkYFaA",
        permanent: false,
        basePath: false,
      },
      {
        source: "/26_carluke_survey",
        destination: "https://forms.gle/pYCMYaxauXTvN9jf6",
        permanent: false,
        basePath: false,
      },
      {
        source: "/32_carluke_survey",
        destination: "https://forms.gle/gb4pcmrPYAuHHEX16",
        permanent: false,
        basePath: false,
      },
      {
        source: "/38_carluke_survey",
        destination: "https://forms.gle/bKspW7CeyTK6CLTk8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/25_selby_survey",
        destination: "https://forms.gle/FoD1TpsgnUbFMfXm8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/20_carlton_survey",
        destination: "https://forms.gle/VietFN6KMqMqn3uF9",
        permanent: false,
        basePath: false,
      },
      {
        source: "/25_wood_survey",
        destination: "https://forms.gle/EfHUg3C9pKvxJoEF7",
        permanent: false,
        basePath: false,
      },
      {
        source: "/66_isabella_survey",
        destination: "https://forms.gle/PBiJveGUXZvsvhGH6",
        permanent: false,
        basePath: false,
      },
      {
        source: "/88_spadina_survey",
        destination: "https://forms.gle/bpotAdPfyTMfYCQR8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/90_adelaide_survey",
        destination: "https://forms.gle/Pmaq3ZRdJSMXAEtJ6",
        permanent: false,
        basePath: false,
      },
      {
        source: "/100_roehampton_survey",
        destination: "https://forms.gle/vSeaMcTTkdsoH6fN7",
        permanent: false,
        basePath: false,
      },
      {
        source: "/100_spadina_survey",
        destination: "https://forms.gle/Z4edGEtQ968p5dTD6",
        permanent: false,
        basePath: false,
      },
      {
        source: "/221_balliol_survey",
        destination: "https://forms.gle/eLq9zNLhtHLHnTgG7",
        permanent: false,
        basePath: false,
      },
      {
        source: "/265_balliol_survey",
        destination: "https://forms.gle/jR6wnSLVtH9vYudR8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/550_jarvis_survey",
        destination: "https://forms.gle/ZWaNTvvHGNEAprM89",
        permanent: false,
        basePath: false,
      },
      {
        source: "/25_nicholas_survey",
        destination: "https://forms.gle/57UQoVwhPYNRQaqF9",
        permanent: false,
        basePath: false,
      },
      {
        source: "/2304_weston_survey",
        destination: "https://forms.gle/Y7CPKjcUoJByGuX39",
        permanent: false,
        basePath: false,
      },
      {
        source: "/235_bloor_survey",
        destination: "https://forms.gle/kC7qHe4KhWCCTqjB8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/66_broadway_survey",
        destination: "https://forms.gle/qdBYZ8BLMzGtNc428",
        permanent: false,
        basePath: false,
      },
      {
        source: "/134_lawton_survey",
        destination: "https://forms.gle/XT3KLSryiBmJT6Ex8",
        permanent: false,
        basePath: false,
      },
      {
        source: "/310_tweedsmuir_survey",
        destination: "https://forms.gle/K6g68Jwe5F4w77Z26",
        permanent: false,
        basePath: false,
      },
      {
        source: "/320_tweedsmuir_survey",
        destination: "https://forms.gle/HawRcAwvRxmiKGzeA",
        permanent: false,
        basePath: false,
      },
    ];
  },
};
